remote_theme: just-the-docs/just-the-docs@v0.10.1
title: Tyk CLI
description: A powerful command-line interface for managing Tyk APIs and configurations

# GitHub Pages base configuration
url: https://sedkis.github.io
baseurl: /tyk-cli

# Minimal Just the Docs options
search_enabled: true
nav_sort: case_insensitive
aux_links:
  GitHub:
    - https://github.com/sedkis/tyk-cli
